name: GGraph
version: 0.0.0
date: 2022-23-07
description: |
    GGraph/Graphs Defined on Groups Package

authors:
    - name: Pedro H. A. Trindade
      url: https://github.com/pedrotrin13334
    - name: M. Laura da Silva
      url: https://github.com/Laura-boot

maintainers:
    - name: Pedro H. A. Trindade
      url: https://github.com/pedrotrin13334
    - name: M. Laura da Silva
      url: https://github.com/Laura-boot

GAP: "4.11"

needed-pkgs:
    - name: "GAPDoc"
      version: "1.5"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"
    - name: "Grape"
      version: "4.8.5"
      url: "https://gap-packages.github.io/grape/"

www: https://pedrotrin13334.github.io/GGraph/
readme: README.md
packageinfo: https://gap-packages.github.io/example/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/example/releases/download/v4.3.1/

abstract: |
    The <span class="pkgname">GGraph</span> package, is a package to create, analyze and operate over graphs defined on abstract groups. a <span class="pkgname">GAP</span>    package. It allows the construction of many different graphs defined on groups found in the academic literature.

status: deposited
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
